kipoi/kipoi

kipoi/model.py

this will allow the user to override the backend setting in the model.yaml file by setting the env variable before

Override the keras backend env variable if not set

---

kipoi/data.py
kipoi/data_utils.py
tests/test_013_data_utils.py
tests/test_12_dataloader_classes.py

before, the iter_cycle was used with `itertools.tee` method. This caused the dataloader to keep the loaded samples in memory.

fix: train_iter now leveraging iterables

---

kipoi/postprocessing/variant_effects/utils/generic.py

@Avsecz, the last unicode related fix breaks python3. The quick hack in this PR should handle it more gracefully.  In the mean time, maybe using the "six" (python compatibility lib for 2 and 3)  or remove python2.7 dependence eventually is the way to go

Unicode fix

---

kipoi/cli/env.py
kipoi/cli/parser_utils.py
kipoi/remote.py
tests/test_23_kipoi_env.py

Enables to specify: `kipoi env create MaxEntScan`. This will merge the dependencies for all submodels (`MaxEntScan/5prime` and `MaxEntScan/3prime` in this case)

Enabled models to be installed by referring to a wildcard

---

docs/templates/using/01_Getting_started.md

I added a bit of text to `01_Getting_started.md` just following the `get_model` example, which specifies the directory argument must have a`model.yaml` file.  This references kipoi/models#103.

added aside about get_model directory

---

example/models/extended_coda/dataloader.yaml
example/models/extended_coda/model.yaml
example/models/iris_model_template/dataloader.yaml
example/models/iris_tensorflow/dataloader.yaml
example/models/iris_tensorflow/model.yaml
example/models/kipoi_dataloader_decorator/dataloader.py
example/models/non_bedinput_model/dataloader.yaml
example/models/pyt/dataloader.yaml
example/models/pyt/model.yaml
example/models/rbp/dataloader.yaml
example/models/rbp/model.yaml
example/models/sklearn_iris/dataloader.yaml
example/models/sklearn_iris/model.yaml
example/models/tal1_model/dataloader.yaml
example/models/var_seqlen_model/dataloader.yaml
kipoi/data.py
kipoi/model.py
kipoi/specs.py
kipoi/utils.py
tests/test_utils_load_module.py

Implements the following API:
Dataloder 
```yaml
type: Dataset  # optional. Only required when specifying a python generator or a function
defined_as: dataloader.SplicingKmerDataset  # Changed from dataloader.py::SplicingKmerDataset
args:
gtf_file:
doc: file path; Genome annotation GTF file
example: example_files/hg19.chr22.gtf
fasta_file:
doc: Reference Genome sequence in fasta format
example: example_files/hg19.chr22.fa  # used for testing
default:  # used as a default on normal runtime   #  added attribute
url: path_to_fasta
md5: ....
```
Custom model
```yaml
defined_as: model.HALModel
args:
weights:
url: url
md5:
other_arg:
default:
url: url
md5:
other_arg2: 10
```
Keras model:
```yaml
defined_as: kipoi.model.KerasModel
args:
weights:
url: ...
```

Unify loading

---

kipoi/model.py

- kerasModel.input_grad support keras2.2. Changes made through changing `_batch_to_list` and `_get_feed_input_names` function.

kerasModel.input_grad support keras2.2

---

.circleci/config.yml
kipoi/__init__.py
kipoi/cli/main.py
kipoi/cli/singularity.py
setup.cfg
setup.py
tests/cli/test_singularity.py

Adds `--singularity` to `kipoi predict`
```bash
kipoi get-example Divergent421 -o example
kipoi predict Divergent421 \                                                                                 
--dataloader_args='{"intervals_file": "example/intervals_file", "fasta_file": "example/fasta_file"}' \
-o '/tmp/output.tsv' \
--singularity
kipoi predict Basset \                                                                                 
--dataloader_args='{"intervals_file": "example/intervals_file", "fasta_file": "example/fasta_file"}' \
-o '/tmp/output.tsv' \
--singularity
```
- SINGULARITY_CACHEDIR was set to `singularity_cache` (https://singularity.lbl.gov/build-environment)
```bash
INFO [kipoi.cli.main] Running kipoi predict in the singularity container
INFO [kipoi.cli.singularity] …
```

Singularity

---

.circleci/conda-env.yml
kipoi/external/related/fields.py
setup.py

The keyword ```convert``` in ```attr.attrib``` is deprecated since 2019/01. `converter` has been introduced in  [17.4.0](http://www.attrs.org/en/stable/changelog.html#id44). This PR uses a try except block to first try the new non-deprecated kw, if this fails with a ```TypeError``` (due to a missing kw on a old  attr version ( < 17.4.0)) we catch that in the except block and use the old deprecated kw.

use converter in favour of deprecated convert in attr.attrib

---

CONTRIBUTING.md
setup.py

This PR tries to fix the installation / contribution step presented in `CONTRIBUTING.md`.
Initially I tried to add all missing things to the setup.py this did not work out so far, I could not add `genomelake` and `cyvcf2`
- added some missing test requirements to `setup.py` which are needed by some unit tests :
-   zarr
-   kipoi_interpret 
-  <del> genomelake </del>
-  <del>cyvcf2 </del>
- adding genomelake and/or cyvcf2 to pip leads to errors on circle-ci, also
on my ubuntu machine with a fresh conda enviroment I get some linker errors when trying to install `cyvcf2` via pip. The error boils down to:
`/home/foobar/miniconda3/envs/k35/compiler_compat/ld: cannot find -lbz2` . Installing `cyvcf2` (and `genomelake`) via conda works fine, this is why I added  `conda install -c bioconda …

updated setup.py dependencies

---

tests/cli/test_singularity.py

The current failure of the tests on circle ci due to #426 seem to come from a the singularity tests.
Here we skip the failing test to at least verify that the rest of the test suite is fine.
Locally the test works fine btw

temporary disable particular singularity test which fails on circle ci

---

kipoi/external/torchvision/dataset_utils.py

This PR improves backward compatibility:
to still use the following code in the models:
```python
from kipoi_utils.external.torchvision.dataset_utils import download_url
```
we add the `dataset_utils.py` to kipoi but import the content from kipoi_utils

better backward comp

---

kipoi/model.py

for new keras / tf version `  K.set_image_dim_ordering(self.image_dim_ordering)` will fail with an attributeError since `set_image_dim_ordering` is not available any more.
think we can just not call `set_image_dim_ordering` in the case of `tf` dim ordering.

hotfix for recent keras tf combination

---

kipoi/cli/main.py

try except to handle the below error
`Traceback (most recent call last):
File "/usr/local/bin/kipoi", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/kipoi/__main__.py", line 105, in main
command_fn(args.command, sys.argv[2:])
File "/usr/local/lib/python3.6/dist-packages/kipoi/cli/main.py", line 368, in cli_info
dl_descr = md.default_dataloader.get()
File "/usr/local/lib/python3.6/dist-packages/kipoi/specs.py", line 785, in get
obj = load_obj(self.defined_as)
File "/usr/local/lib/python3.6/dist-packages/kipoi_utils/utils.py", line 140, in load_obj
fp, pathname, description = imp.find_module(module_name)
File "/usr/lib/python3.6/imp.py", line 297, in find_module
raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'kipoiseq'`

try except block to catch kipoiseq ImportError

---

kipoi/env_db.py

Hello, I'm having an issue with TinyDB object does not have a method called 'purge'. Seems like it is deprecated. So I just update it to truncate() instead. Can you please check?  Issue is similar to #502

Update tinydb purge method to truncate

---

.circleci/config.yml
dev-requirements-py36.yml

I had to explicitly add gcc inside the environment. I suspect it is due to an updated conda version. I intentionally did not pin the version because we most likely would want to know if the setup fails for a certain version of conda.
Any opinion?

Nightly CI fixed

---

dev-requirements-py36.yml
kipoi/cli/main.py
kipoi/model.py
kipoi/pipeline.py
tests/test_13_data_examples.py

Although the conda environment, base docker container and pytorch version are identical  between last successful run and now, for some reason floats are misinterpreted as doubles. I have fixed it but the fix is a bit hacky. However, none of the models are complaining https://app.circleci.com/pipelines/github/kipoi/models/835/workflows/20210196-6f06-4518-a042-2eed1ec66e4c. I am merging this for now but we can discuss further if you know of a better solution

Fixed ci for python3.6

---

.circleci/config.yml
dev-requirements-py36.yml
dev-requirements-py37.yml

It seems for python 3.7  installing conda environment is running out of memory inside the docker executor. Installing matplotlib separately seems to do the trick. I am merging this for now but I will experiment with a machine executor which has more RAM (7.5 GB) than docker executor (4 GB) in a separate attempt.

Fixed ci for python 3.7

---

.circleci/config.yml
dev-requirements-py37.yml

The main issue stemmed from running out of memory while installing matplotlib along with installing other packages in dev-requirements-py37.yml. Machine executors in circleci has about 7.5 GB RAM as opposed to the docker executors which has about 4 GB RAM. I think for the sake of homogeneity we should change test-py36-yml to use machine executor as well but for now it is okay. 
PS: I am merging this to master for now but any comment is welcome.

Add machine executor for testing with python 3.7

---

.circleci/config.yml

I changed the base docker image from continuumio/miniconda3:4.5.12 to  continuumio/miniconda3:4.7.10.  Now all tests across kipoi and models repo uses miniconda3:4.7.10 as base conda version

Upgrading base docker image of multiple tests

---

kipoi/cli/source_test.py
kipoi/sources.py

This bug manifested in the nightly test of model repo. Check [here](https://app.circleci.com/pipelines/github/kipoi/models/873/workflows/84fdc68e-5ad9-4562-afda-0e62aaa587aa/jobs/2796)
The main error was -
```
ERROR [kipoi.cli.source_test] Model <model-name?> failed: 'module' object is not subscriptable
```
This issue did not show up in any unit test in kipoi repo which shows perhaps not every crucial part of the codebase is coevred by unit tests.

Fixed ci of model repo

---

dev-requirements-py36.yml
dev-requirements-py37.yml
dev-requirements-py38.yml
dev-requirements-py39.yml

pyranges' latest release has a typo which caused all the tests to fail. For now, I have pinned pyranges to use last stable version and have opened an issue [here](https://github.com/biocore-ntnu/pyranges/issues/218). I will revert this change once its fixed.

Fixed ci by pinning pyranges

---

README.md
dev-requirements-py36.yml
dev-requirements-py37.yml
kipoi/readers.py

For python 3.6 and 3.7 h5py version must be < 3.*, otherwise pretrained models of type kipoi.model.KerasModel and kipoi.model.TensorflowModel can not be loaded. 
A related bug report: [here](https://github.com/tensorflow/tensorflow/issues/44467)

Bugs related to h5py/python version addressed

---

dev-requirements-py36.yml
dev-requirements-py37.yml
dev-requirements-py38.yml
dev-requirements-py39.yml
kipoi/writers.py
setup.py
tests/test_161_writers.py

This PR adds support for writing parquet files.
In particular, it adds two additional parquet writer implementations:
- `ParquetFileBatchWriter`: Writes to a single parquet file and depends on PyArrow.
- `ParquetDirBatchWriter`: Writes a directory of parquet files using `pandas.to_parquet()`. Supports both PyArrow and fastparquet. This implementation is predestined for multi-processing / asynchronous writing since no file-locking is necessary for it. Nevertheless, I'm not sure yet how Kipoi would take advantage of that.
My very long-term goal is that we directly provide schemas as Arrow schemas to be able to pass them around cross-language without any kind of conversion/serialization:
https://arrow.apache.org/docs/python/api/datatypes.html
This PR is the first step in that direction. …

add support for writing parquet files

---

tests/cli/test_singularity.py

Since we are running into issues with circleci's  1 hour time limit  restrictions choosing a smaller singularity image should be  helpful.

Use a smaller singularity image for tests

---

.circleci/config.yml
dev-requirements-py310.yml
kipoi/kipoidescriptionhelper.py
kipoi/kipoimodeldescription.py
kipoi/metadata.py
kipoi/model.py

More fixes with collections and a preliminary conda environment. A new sets of tests have not been added in ci because for now pytorch is not available in python 3.10.

Fixes for python 3.10

---

dev-requirements-py37.yml

For some reason, tests involving pyarrow have been flaky only in `python=3.7` environment. I checked that on occasions when these tests failed, somehow pyarrow 0.11 was installed which is rather old. For now, I am pinning pyarrow to its current version `7.0.0`. For now, the tests are passing and I will continue to monitor the flakyness.

Attempt to fix flaky tests

---

.circleci/config.yml

There were two problems
1. Context was missing - SYNC_TOKEN is a context specific environment variable.
2. Github has changed its repository dispatch event url - see [here](https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event). Needed to update the CURL statement. However, I somehow could not make circleci parse the yaml with line break.

Fixing issues with triggering build-release-push workflow of kipoi-containers repo from this repo

---

setup.py

Thanks to @[ccoulombe](https://github.com/ccoulombe) and #685 for bringing this to my attention.
It seems dataclasses was an unnecessary dependency. I will shortly release a new version.

Removing dataclasses from setup.py

---

dev-requirements.yml
setup.py

- attrs recently released a version which drops support for python 2. attrs is used by related which is used by kipoi. Unfortunately related is no longer being maintained. See [here](https://github.com/genomoncology/related/issues/55). I fixed it by pinning attrs to the previous version that worked. 
- Older release of keras (2.8) does not automatically install keras_preprocessing with conda anymore which in turn failed test_10_kipoimodel.py. This has been taken care of in the current release (2.9) - so I upgraded dev-requirements.yml.

Fixed kipoi installation

---

.circleci/config.yml

This fixes the `conda clean` error in tests.

Remove deprecated `conda clean` flag `-s` from circleCI

---

dev-requirements-py36.yml
dev-requirements-py37.yml
dev-requirements.yml

This should fix the issue regarding the failing 3.7 test. The goal here is to use a version of `zarr` that supports 3.7.

Set `zarr` version to 2.12.0
