kipoi/kipoi

kipoi/cli/source_test.py

sort the models alphabetically before testing in `kipoi test-source`

sort test_models

---

kipoi/cli/env.py

add random string to the tmp yaml file path

---

kipoi/cli/source_test.py
kipoi/conda.py

bedtools was not activated correctly. fixes kipoi/models builds

fix: test-source environment activation

---

kipoi/cli/main.py

fix keep_inputs for `kipoi predict`

---

.circleci/config.yml
README.md
setup.py

add coveralls

---

kipoi/model.py
tests/test_14_PyTorchModel.py
tests/test_15_TensorFlowModel.py
tests/test_16_KerasModel.py

Added layer activation inspection for Keras, PyTorch and TensorFlow. Only Keras so far supports pre_nonlinearity=True.

Layer activation inspection

---

examples/pyt/model_files/pyt.py
kipoi/cli/main.py
kipoi/model.py
tests/test_14_PyTorchModel.py
tests/test_20_cli_examples.py

added --layer option to `kipoi predict`

---

kipoi/cli/env.py
kipoi/components.py

fix: pytorch-cpu not found, closes #271

---

.circleci/config.yml
setup.py

Freeze  urllib3 dependency so that `requests` package works. This will have to be update/removed at a later stage again.

Fix urllib3 dep

---

kipoi/cli/postproc.py
kipoi/pipeline.py
kipoi/postprocessing/gradient_vis/vis.py
tests/test_101_pipeline.py
tests/test_14_PyTorchModel.py
tests/test_20_cli_examples.py
tests/test_301_gradient_vis.py

- Add `input_grad` pipeline 
- rename `preds` to `grads` when results of `input_grad` are stored in a hdf5 file.

Add pipeline for input grad

---

kipoi/cli/source_test.py
kipoi/components.py
tests/test_012_conda_env.py
tests/test_23_kipoi_env.py

closes https://github.com/kipoi/kipoi/issues/292

handle channel ordering

---

kipoi/cli/env.py
kipoi/cli/main.py
kipoi/remote.py
tests/test_23_kipoi_env.py

implemented generic pull.

---

kipoi/sources.py

Retain author order in model groups

---

example/models/iris_tensorflow/model.yaml
kipoi/model.py
kipoi/specs.py
kipoi/utils.py
tests/test_utils_recursive_parse.py

Specify remote files in kipoi.model.TensorFlowModel. Closes https://github.com/kipoi/kipoi/issues/351
```yaml
defined_as: kipoi.model.TensorFlowModel
args:
input_nodes:
features: inputs  # input = dictionary of np.arrays
target_nodes: probas  # output = np.array
checkpoint_path:
meta:
url: https://github.com/kipoi/kipoi/blob/master/example/models/iris_tensorflow/model_files/model.ckpt.meta?raw=true
md5: 38760b7242b10111af97dcfc00f1acd7
index:
url: https://github.com/kipoi/kipoi/blob/master/example/models/iris_tensorflow/model_files/model.ckpt.index?raw=true
md5: 1eba18803dc1d799a0464f8fc7c0c90a
data:
url: https://github.com/kipoi/kipoi/blob/master/example/models/iris_tensorflow/model_files/model.ckpt.data-00000-of-00001?raw=true
md5: fc1e7daac0c122dac59e1988f2ba3422
```
Example: …

Tensorflow files

---

kipoi/model.py
kipoi/sources.py

fixes download path for model source

fix download path

---

example/models/multiple_models/model-template.yaml
kipoi/cli/env.py
kipoi/specs.py

- fix the scenario when the package from which we are importing the dataloader is not installed

handle the case when kipoiseq is not installed

---

docs/templates/contributing/02_Writing_model.yaml.md
example/models/multiple_models/model-template.yaml
kipoi/external/torchvision/dataset_utils.py
kipoi/specs.py
tests/test_20_cli_examples.py
tests/test_22_kipoi_test_source.py

- fix the master build
- prepare kipoi tests to use the new kipoi/models version

use kipoiseq=0.2.1 names

---

kipoi/cli/main.py
kipoi/data.py
kipoi/model.py
kipoi/pipeline.py
kipoi/sources.py
kipoi/specs.py
kipoi/utils.py
kipoi/writers.py
tests/test_101_pipeline.py
tests/test_161_writers.py
tests/test_utils_load_module.py

- added `kipoi.writers.Multiplebatchwriter`
- added `kipoi.pipeline.predict_to_file`
- added `kipoi.writers.get_writer` (by refactoring it from `kipoi.cli.main.cli_predict`)
- `kipoi.utils.override_default_kwargs` now returns a function copy  instead of modifying the class inplace

Predict to file

---

kipoi/conda.py
kipoi/config.py
kipoi/external/related/mixins.py
kipoi/sources.py
kipoi/specs.py
tests/specs/parsing/test_021_parsing_Info.py
tests/test_012_conda_env.py
tests/test_22_kipoi_test_source.py

- add `dependencies` to model source' `config.yaml` file
- display a warning if the dependency is not satisfied
- merge `GitLFSSource` and `GitSource` into `GitSource` with `use_lfs` flag
- add `auto_update` flag to model source

Model source migration

---

kipoi/cli/env.py
kipoi/conda/env_db.py
kipoi/conda/utils.py
tests/test_20_cli_examples.py

Fixes the following error when creating a new conda environmnent:

replace get_env_cli with existing get_kipoi_bin

---

kipoi/cli/source_test.py

Added `--common_env` to `kipoi test-source` to test common environments.

added --common_env

---

.circleci/config.yml
kipoi/writers.py
tests/test_161_writers.py

added: parquet io

---

kipoi/cli/env.py
tests/test_23_kipoi_env.py
tests/test_24_env_db.py

Fixes https://github.com/kipoi/kipoi/issues/389

store only model names for kipoi models

---

envs/Singularity
kipoi/cli/env.py
kipoi/cli/source_test.py
tests/test_20_cli_examples.py

Added `kipoi env create all` command

Env create all

---

kipoi/cli/main.py
kipoi/data.py
kipoi/specs.py

Don't load the model when running `kipoi info`

Fix kipoi info

---

kipoi/writers.py
tests/test_161_writers.py

- Implements AsyncWriter as described here: https://github.com/kipoi/kipoi-veff/issues/27

added AsyncBatchwriter

---

kipoi/specs.py

moved external.torchvision imports up

---

.circleci/conda-env.yml
kipoi/__main__.py
kipoi/cli/env.py
kipoi/cli/main.py
kipoi/conda/env_db.py
kipoi/config.py
kipoi/data.py
kipoi/external/related/mixins.py
kipoi/model.py
kipoi/pipeline.py
kipoi/sources.py
kipoi/specs.py
kipoi/utils.py
notebooks/gradient_prediction.ipynb
setup.py

in PR #420 and #421  I get errors from circle-ci in ```tests/test_161_writers.py``` claiming that pandas has no ```pandas.read_parquet ```.
Since ```read_parquet``` has been introduced in 0.21.0 it might be useful to require a version of pandas >=0.21.0

Pin pandas

---

kipoi/writers.py
tests/test_161_writers.py

Fixes BigWigWriter. Segmentation fault was raised due to the header lack

fix BigWigWriter

---

kipoi/writers.py

I noticed that the [`AsyncBatchWriter`](https://github.com/kipoi/kipoi/blob/a8886e5be0ddc46a482d6803ea4e3695fe7759d7/kipoi/writers.py#L92) has a strange implementation where one has to guess the time `close_wait` the writer needs to get the job done:
-  If a job finishes faster, we will wait `close_wait` anyhow since  `batch = q.get()` in the `_writer_worker` will block if there is nothing on the Queue.
- If a job takes longer than `close_wait`, well ... bad things I would assume since `self.process.join(self.close_wait) ` will just kill the Process after the time `close_wait`.
I would argue this is bad in both cases.
This PR tries to fix this with the following:
- using a   [`JoinableQueue`](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.JoinableQueue)
- call …

Better AsyncBatchWriter

---

kipoi/model.py

fix typo in _get_standardize_input_data_func()

fix continuous integration

---

kipoi/writers.py
tests/test_161_writers.py

Fixes https://github.com/kipoi/kipoi/issues/457.

Add variable-length data type support for HDF5BatchWriter

---

dev-requirements-py36.yml
setup.py

It looks like tests are passing.

h5py version is pinned to 2.10.0

---

kipoi/cli/main.py
tests/test_20_cli_examples.py

Fixing kipoi_metadata cli

---

kipoi/cli/source_test.py

Parallel test source cli

---

kipoi/cli/main.py
kipoi/data.py
kipoi/model.py
kipoi/pipeline.py
kipoi/sources.py
kipoi/specs.py
kipoi/writers.py

Closes: #593 
I did not add any cli parameter. Let me know if you would like one.
An example is [here](https://github.com/kipoi/models/blob/add-test-predictions/Basenji/model.yaml#L83-L84)

Adjust  chunk size for .h5 files

---

.circleci/config.yml
dev-requirements-py37.yml
kipoi/model_template/{{cookiecutter.model_name}}/dataloader.py
tests/test_21_kipoi_init.py

Only two tests needed to be altered. I will change the ReadME once this pr is approved. Models seems to have done alright it seems - https://app.circleci.com/pipelines/github/kipoi/models/818/workflows/e5afe0cc-7590-4f13-8a79-49a096c27ddf

Adding support for python 3.7

---

example/models/pyt/dataloader.py
kipoi/cli/main.py
kipoi/model.py
kipoi/pipeline.py

The issue was for pyt, the input data type is converted to np.float64 by kipoiseq's one_hot_dna. This problem seems to have been corrected by https://github.com/kipoi/kipoiseq/pull/99. Once a new version of kipoiseq is published I will undo this change.

Bug fix for input data type discrepancy

---

.circleci/config.yml

Advantage - 7.5 GB RAM vs 4 GB RAM in docker instances
Disadvantage - Take a bit longer to launch than docker instances

Replaced docker executer with machine executor in ci

---

dev-requirements-py36.yml
dev-requirements-py37.yml
dev-requirements-py38.yml
dev-requirements-py39.yml

New pyranges version has been released where the typo is fixed. Reverting pinning pyranges version in this pr.

Revert "Fixed ci by pinning pyranges"

---

.circleci/config.yml
kipoi/cli/singularity.py
kipoi/cli/source_test.py
tests/cli/test_singularity.py
tests/test_22_kipoi_test_source.py

Add singularity to kipoi-predict and make it compatible with the multi container setup

---

docs/templates/using/cli.md

I just copied @haimasree's awesome explanation from here:
https://github.com/kipoi/models/pull/293#issuecomment-1017284494

Add detailed documentation to `test` command

---

.circleci/config.yml
dev-requirements-py310.yml
kipoi/kipoidataloaderdescription.py

- A new conda environment has been added. Quite a few packages are still not available in conda - so for now I am installing them from pip. This will be taken care of in future as per their availability
- Few more bug fixes for compatibility with python 3.10

Adding tests and support for python 3.10

---

.circleci/config.yml

Adding a provision to auto update containers when kipoi has a new version release

---

kipoi/specs.py
tests/specs/parsing/test_028_parsing_Dependencies.py

Fix pytorch-cpu and pysam discrepancies
